items = {
    "hello": "Hello, {firstname}.",
    "number_of_friends": "You have {friends_count} contacts.",
    "add_friend": "Add",
    "cancel": "Cancel",
    "settings": "Settings",
    "language": "Language",
    "add_drawer_title": "Add a new contact!",
    "edit_drawer_title": "Edit info about a contact!",
    "add_drawer_fullname": "Full name",
    "add_drawer_nickname": "Nickname",
    "add_drawer_birthday": "Birthday",
    "add_drawer_birthday_day": "Day",
    "add_drawer_birthday_month": "Month",
    "add_drawer_birthday_year": "Year",
    "add_drawer_phone": "Phone",
    "add_drawer_location": "Location",
    "delete": "Yes, delete",
    "delete_title": "Delete a contact?",
    "delete_description": "Are you sure you want to remove {fullname} from your circle? This action cannot be undone.",
    "save": "Save",
    "months": [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
        ],

}