items = {
    "hello": "سلام، {firstname}.",
    "number_of_friends": "شما {friends_count} مخاطب دارید.",
    "add_friend": "افزودن",
    "cancel": "لغو",
    "settings": "تنظیمات",
    "language": "زبان",
    "add_drawer_title": "یک مخاطب جدید اضافه کنید!",
    "edit_drawer_title": "اطلاعات یک مخاطب را ویرایش کنید!",
    "add_drawer_fullname": "نام کامل",
    "add_drawer_nickname": "لقب",
    "add_drawer_birthday": "تاریخ تولد",
    "add_drawer_birthday_day": "روز",
    "add_drawer_birthday_month": "ماه",
    "add_drawer_birthday_year": "سال",
    "add_drawer_phone": "شماره تلفن",
    "add_drawer_location": "محل زندگی",
    "delete": "حذف کن",
    "delete_title": "حذف یک مخاطب؟",
    "delete_description": "آیا از حذف مخاطب {fullname} اطمینان دارید؟ این عمل قابل بازگشت نیست.",
    "save": "ذخیره",
    "months": [
            "فروردین",
            "اردیبهشت",
            "خرداد",
            "تیر",
            "مرداد",
            "شهریور",
            "مهر",
            "آبان",
            "آذر",
            "دی",
            "بهمن",
            "اسفند",
        ],
}